name = "favmoji"
main = "src/index.ts"
compatibility_date = "2023-01-19"
usage_model = "bundled"
env = { }
routes = [
  { pattern = "favmoji.chowie.net", custom_domain = true },
]

[triggers]
crons = [ ]
